// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mono PCM frame streamed from Rust to JS. JS owns all DSP (pitch, reactive
 * analysis) and runs it on a sliding window built from these frames.
 */
export type MicSampleFrame = { sample_rate: number, samples: Array<number>, };
